#!/usr/bin/env node
/**
 * Cordova Hook: before_prepare/inject_version.js
 *
 * Reads the app version from config.xml and writes it to
 * www/js/core/app-version.js so the web app can consume it
 * at runtime via window.APP_VERSION — no more manual edits!
 *
 * Runs automatically on: cordova prepare / cordova build
 * Can also be run manually: node hooks/before_prepare/inject_version.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Locate files ────────────────────────────────────────────────
const rootDir    = path.resolve(__dirname, '..', '..');
const configPath = path.join(rootDir, 'config.xml');
const outPath    = path.join(rootDir, 'www', 'js', 'core', 'app-version.js');

// ── Read config.xml ─────────────────────────────────────────────
if (!fs.existsSync(configPath)) {
    console.error('[inject_version] config.xml not found at', configPath);
    process.exit(0); // non-fatal: don't abort build
}

const xml     = fs.readFileSync(configPath, 'utf8');
const match   = xml.match(/<widget[^>]+version="([^"]+)"/);
const version = match ? match[1] : '0.0.0';

// ── Write app-version.js ────────────────────────────────────────
const content = `// AUTO-GENERATED by hooks/before_prepare/inject_version.js
// DO NOT EDIT manually — change version in config.xml instead.
// Generated: ${new Date().toISOString()}

window.APP_VERSION = "${version}";
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`[inject_version] window.APP_VERSION = "${version}" → ${path.relative(rootDir, outPath)}`);
